nodes:
  0:
    x: 0.61
    y: -0.21
    yaw: 0.0
  1:
    x: 2.36
    y: 1.24
    yaw: 1.245
  2:
    x: 3.01
    y: 0.39
    yaw: 0.038
  3:
    x: 1.96
    y: -1.21
    yaw: -2.175
  4:
    x: 3.51
    y: -2.06
    yaw: 2.562
edges:
- from: 0
  to: 2
- from: 2
  to: 4
- from: 3
  to: 2
- from: 1
  to: 4
- from: 3
  to: 0
