nodes:
  0:
    x: 0.51
    y: -0.11
    yaw: 3.038
  1:
    x: 2.06
    y: 1.34
    yaw: 1.427
  2:
    x: 3.11
    y: 0.39
    yaw: -2.832
  3:
    x: 1.56
    y: -0.91
    yaw: -0.529
  4:
    x: 4.81
    y: -1.56
    yaw: -2.686
edges:
- from: 1
  to: 3
- from: 3
  to: 4
- from: 2
  to: 0
- from: 2
  to: 3
- from: 0
  to: 1
